CREATE TABLE IF NOT EXISTS access_invites (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text NOT NULL UNIQUE,
    invited_by text,
    is_active boolean NOT NULL DEFAULT true,
    invited_at timestamptz NOT NULL DEFAULT now(),
    accepted_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    notes text
);

CREATE INDEX IF NOT EXISTS idx_access_invites_active
    ON access_invites (is_active, email);

-- Příklad: vytvoření pozvánky pro nového uživatele
INSERT INTO access_invites (email, invited_by, is_active, notes)
VALUES ('vas-email@example.com', 'admin', true, 'Pozvánka pro přístup do aplikace');

-- Příklad pro přidání dalšího uživatele:
-- INSERT INTO access_invites (email, invited_by, is_active, notes)
-- VALUES ('novy@email.cz', 'admin', true, 'Pozvánka pro dalšího člena domácnosti');
